In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Importing Libraries

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
%matplotlib inline

In [3]:
df = pd.read_csv("../input/titanic/train.csv")

In [4]:
df.sample(5)

### About the columns
* Variable --> Definition --> Key
* survival --> Survival --> 0 = No, 1 = Yes
* pclass --> Ticket class --> 1 = 1st, 2 = 2nd, 3 = 3rd
* sex --> Sex --> 
* Age --> Age in years --> 
* sibsp --> # of siblings / spouses aboard the Titanic --> 
* parch --> # of parents / children aboard the Titanic --> 
* ticket --> Ticket number --> 
* fare --> Passenger fare --> 
* cabin --> Cabin number --> 
* embarked --> Port of Embarkation --> C = Cherbourg, Q = Queenstown, S = Southampton

In [5]:
df.info()

In [6]:
pd.isna(df).sum()

In [10]:
# Now if we sort them for our convinience
(pd.isna(df).sum().sort_values(ascending = False)/len(df)*100).to_frame()

### Here we get to know about the percent of missing valued from each column, and will also treat them as required.

In [22]:
plt.figure(figsize = (10,8))
sns.countplot(df.Survived)

In [36]:
survived_perc=len(df[df.Survived == 1])/len(df)*100
non_survived_perc = len(df[df.Survived == 0])/len(df)*100
print(f"Total percentage of survivors = {survived_perc}")
print(f"Total percentage of deaths = {non_survived_perc}")
plt.figure(figsize = (8,6))
plt.pie([survived_perc,non_survived_perc],labels = ["Survived","Not Survived"], autopct='%.2f%%')
plt.show()

In [72]:
plt.figure(figsize = (10,8))
plt.pie([len(df[df.Sex=='male']),len(df[df.Sex=='female'])],labels = ["Male","Female"], autopct='%.2f%%')
plt.show()

In [40]:
# Maximum and minimum age of passengers
print(f"Maximum Passenger age is = {df.Age.max()} years")
print(f"Minimum Passenger age is = {df.Age.min()} years")

In [43]:
# Is survival rate has any corelation with age ??
plt.figure(figsize=(10,8))
sns.scatterplot(x= df.Age, y=df.Survived)

In [44]:
# Is survival rate has any corelation with fare ??
plt.figure(figsize=(10,8))
sns.scatterplot(x= df.Fare, y=df.Survived)

#### As we can see from above the survival rate doesn't depends upon the age or fare rate we can also conclude that the survival rate is not biased

In [56]:
plt.figure(figsize = (15,12))
plt.pie(df.SibSp.value_counts().values,labels = df.SibSp.value_counts().index, autopct='%.2f%%')
plt.show()

In [67]:
# number of parents and children on board
plt.figure(figsize = (10,8))
df.Parch.value_counts().plot.bar()

## From the above plots we can state that the most number of people who boarded the ship were single as the max number have no siblings (can state that most were single child) or spouce and most have no parents along them.

In [70]:
plt.figure(figsize = (10,8))
sns.histplot(df['Fare']);

## Thus most of the fare was around 0 - 100 $ at that time